// Built-in skills (procedural memory, SPEC Layer 4). Each skill is a curated
// "procedure" the agent auto-applies when a task matches it. Distinct from tools
// (atomic functions): a skill is *guidance* injected into the system prompt.
//
// Triggers are lowercase substrings used by the free keyword matcher. Keep
// instructions concise (2-4 sentences) — 1-2 skills are injected per message.

export interface Skill {
  id: string;
  name: string;
  category: string;
  description: string;
  triggers: string[];
  instructions: string;
}

export const BUILTIN_SKILLS: Skill[] = [
  // ── Writing & Communication ─────────────────────────────────────────────
  {
    id: "email-writing",
    name: "Email Writing",
    category: "Writing & Communication",
    description: "Write or reply to emails in the right tone.",
    triggers: ["email", "reply to", "write to", "draft an email", "respond to this message"],
    instructions: "Write a clear email matched to the context's formality. Ask for the recipient and goal if missing. Include a subject line, greeting, a concise body, and a sign-off.",
  },
  {
    id: "summarize",
    name: "Summarize Text",
    category: "Writing & Communication",
    description: "Condense text into a faithful summary.",
    triggers: ["summarize", "summary", "tl;dr", "tldr", "key points", "sum up"],
    instructions: "Lead with a one-sentence gist, then 3-7 bullet key points. Preserve names and numbers. Stay faithful to the source and note any ambiguity.",
  },
  {
    id: "proofread",
    name: "Proofread & Fix Grammar",
    category: "Writing & Communication",
    description: "Correct grammar, spelling, and clarity.",
    triggers: ["proofread", "grammar", "fix my", "correct this", "spelling", "check my writing"],
    instructions: "Fix grammar, spelling, punctuation, and clarity without changing meaning or voice. Return the corrected text, then a short bullet list of the notable changes.",
  },
  {
    id: "rewrite-tone",
    name: "Rewrite / Change Tone",
    category: "Writing & Communication",
    description: "Rephrase text in a different tone or style.",
    triggers: ["rewrite", "reword", "make it sound", "more formal", "more casual", "change the tone", "paraphrase"],
    instructions: "Rewrite to the requested tone (formal, friendly, concise, persuasive) while keeping the original meaning. Offer one or two variants when useful.",
  },
  {
    id: "translate",
    name: "Translate",
    category: "Writing & Communication",
    description: "Translate text between languages naturally.",
    triggers: ["translate", "in spanish", "in thai", "in french", "to english", "translation"],
    instructions: "Translate accurately into the target language, preserving tone and meaning. Prefer natural equivalents for idioms and note any nuance that doesn't carry over.",
  },
  {
    id: "cover-letter",
    name: "Cover Letter",
    category: "Writing & Communication",
    description: "Write a tailored job cover letter.",
    triggers: ["cover letter", "job application", "applying for", "apply for this job"],
    instructions: "Write a tailored cover letter from the user's background and the role. Open with a hook, match 2-3 key qualifications to the job, and close with a call to action. Keep it under one page.",
  },
  {
    id: "resume",
    name: "Resume / CV Help",
    category: "Writing & Communication",
    description: "Write or improve resume content.",
    triggers: ["resume", "cv", "work experience", "bullet points for my", "curriculum vitae"],
    instructions: "Write or improve resume content using strong action verbs and quantified results in concise bullets. Tailor to the target role when given.",
  },
  {
    id: "blog-post",
    name: "Blog / Article Draft",
    category: "Writing & Communication",
    description: "Draft a structured article or blog post.",
    triggers: ["blog", "article", "write a post", "write about", "blog post"],
    instructions: "Draft a structured article: a working title, an intro hook, logical sections with headers, and a conclusion. Match the requested length and audience.",
  },
  {
    id: "social-post",
    name: "Social Media Post",
    category: "Writing & Communication",
    description: "Write platform-appropriate social posts.",
    triggers: ["tweet", "social media", "instagram", "linkedin post", "caption", "facebook post"],
    instructions: "Write posts suited to the platform's length and tone, with relevant hashtags. Front-load the hook and offer a few variations.",
  },
  {
    id: "meeting-notes",
    name: "Meeting Notes / Minutes",
    category: "Writing & Communication",
    description: "Turn raw notes into structured minutes.",
    triggers: ["meeting notes", "minutes", "action items", "meeting recap", "standup notes"],
    instructions: "Turn raw notes or a transcript into structured minutes: attendees (if known), decisions, action items with owners, and follow-ups.",
  },

  // ── Research & Analysis ─────────────────────────────────────────────────
  {
    id: "web-research",
    name: "Web Research",
    category: "Research & Analysis",
    description: "Gather and synthesize current info from the web.",
    triggers: ["research", "find out", "look up", "latest", "what's happening", "current"],
    instructions: "Use the web search and fetch tools to gather current, credible information. Synthesize the findings, cite sources with links, and flag uncertainty or conflicting claims.",
  },
  {
    id: "compare-options",
    name: "Compare Options",
    category: "Research & Analysis",
    description: "Compare choices with a clear recommendation.",
    triggers: ["compare", " vs ", "pros and cons", "which is better", "difference between"],
    instructions: "Build a comparison with criteria as rows and options as columns, plus pros and cons. End with a bottom-line recommendation tied to the user's priorities.",
  },
  {
    id: "explain-concept",
    name: "Explain a Concept",
    category: "Research & Analysis",
    description: "Explain a topic clearly at the right level.",
    triggers: ["explain", "what is", "how does", "eli5", "in simple terms", "help me understand"],
    instructions: "Start with a one-line plain-language definition, then a simple analogy, then key details. Match the requested depth and avoid jargon unless asked.",
  },
  {
    id: "data-analysis",
    name: "Analyze Data",
    category: "Research & Analysis",
    description: "Analyze a dataset and surface insights.",
    triggers: ["analyze", "csv", "dataset", "the data", "trends", "statistics"],
    instructions: "Inspect the data, summarize its structure, compute relevant stats, and surface trends and outliers. Use the code tool for real calculations rather than estimating, and state caveats.",
  },
  {
    id: "extract-info",
    name: "Extract Key Info",
    category: "Research & Analysis",
    description: "Pull structured fields out of a source.",
    triggers: ["extract", "pull out", "find the", "key details from", "parse"],
    instructions: "Extract the requested fields into a clean list or table. Mark missing fields as not found and never invent values.",
  },
  {
    id: "fact-check",
    name: "Fact-Check",
    category: "Research & Analysis",
    description: "Verify a claim against reliable sources.",
    triggers: ["fact check", "is it true", "verify", "debunk", "is this real"],
    instructions: "Assess the claim using reliable sources (use web tools). State a verdict — true, false, misleading, or unverified — with the supporting evidence and links.",
  },
  {
    id: "summarize-sources",
    name: "Summarize Sources",
    category: "Research & Analysis",
    description: "Synthesize multiple papers or sources.",
    triggers: ["literature", "sources", "papers", "references", "studies", "research summary"],
    instructions: "Summarize each source's key claim and method, then synthesize where they agree or disagree. Keep citations and note any gaps.",
  },
  {
    id: "swot",
    name: "SWOT Analysis",
    category: "Research & Analysis",
    description: "Structured strengths/weaknesses analysis.",
    triggers: ["swot", "strengths and weaknesses", "opportunities and threats"],
    instructions: "Produce a SWOT grid (Strengths, Weaknesses, Opportunities, Threats) grounded in the specifics given, then 2-3 strategic takeaways.",
  },

  // ── Productivity & Planning ─────────────────────────────────────────────
  {
    id: "task-breakdown",
    name: "Break Down a Task",
    category: "Productivity & Planning",
    description: "Decompose a goal into concrete steps.",
    triggers: ["break down", "steps to", "how do i", "checklist", "break this into"],
    instructions: "Decompose the goal into ordered, concrete steps with clear done-criteria. Flag dependencies and give a rough effort estimate.",
  },
  {
    id: "project-plan",
    name: "Plan a Project",
    category: "Productivity & Planning",
    description: "Build a realistic project plan.",
    triggers: ["project plan", "roadmap", "timeline", "milestones", "plan the project"],
    instructions: "Produce a plan with objective, phases and milestones, tasks per phase, owners if known, a timeline, and key risks. Keep it realistic.",
  },
  {
    id: "prioritize",
    name: "Prioritize",
    category: "Productivity & Planning",
    description: "Rank tasks by impact and effort.",
    triggers: ["prioritize", "what first", "most important", "triage", "what should i focus on"],
    instructions: "Rank items by impact versus effort (or urgency versus importance). Present a simple matrix and a recommended order with reasoning.",
  },
  {
    id: "brainstorm",
    name: "Brainstorm Ideas",
    category: "Productivity & Planning",
    description: "Generate and group fresh ideas.",
    triggers: ["brainstorm", "ideas for", "suggestions", "come up with", "give me ideas"],
    instructions: "Generate a diverse set of ideas (quantity first), grouped by theme. Then highlight the most promising few with a one-line rationale each.",
  },
  {
    id: "decision-helper",
    name: "Decision Helper",
    category: "Productivity & Planning",
    description: "Weigh options and recommend a choice.",
    triggers: ["should i", "help me decide", "decision", "help me choose", "which option"],
    instructions: "Clarify the options and the user's criteria and weights, build a weighted comparison, and give a clear recommendation with the trade-offs.",
  },
  {
    id: "schedule",
    name: "Plan a Schedule",
    category: "Productivity & Planning",
    description: "Build a realistic time-blocked plan.",
    triggers: ["schedule", "agenda", "time block", "daily plan", "routine", "plan my day"],
    instructions: "Build a realistic time-blocked schedule from the tasks and constraints, with buffers and breaks. Ask for fixed commitments if unknown.",
  },
  {
    id: "goal-setting",
    name: "Set Goals (SMART)",
    category: "Productivity & Planning",
    description: "Turn intentions into SMART goals.",
    triggers: ["goal", "smart goal", "objective", "new year resolution", "set a target"],
    instructions: "Turn intentions into SMART goals (Specific, Measurable, Achievable, Relevant, Time-bound) with milestones and a clear first action.",
  },
  {
    id: "organize-notes",
    name: "Organize Notes",
    category: "Productivity & Planning",
    description: "Restructure messy notes cleanly.",
    triggers: ["organize", "clean up my notes", "structure this", "tidy up", "make sense of"],
    instructions: "Reorganize messy notes into a clear hierarchy with headings and grouped points, pulling out any action items.",
  },

  // ── Coding (basics) ─────────────────────────────────────────────────────
  {
    id: "explain-code",
    name: "Explain Code",
    category: "Coding",
    description: "Explain what a piece of code does.",
    triggers: ["explain this code", "what does this code", "understand this function", "read this code"],
    instructions: "Explain what the code does step by step, its inputs and outputs, and any side effects or edge cases. Point out potential bugs.",
  },
  {
    id: "debug-error",
    name: "Debug an Error",
    category: "Coding",
    description: "Diagnose and fix an error.",
    triggers: ["error", "exception", "traceback", "not working", "bug", "stack trace", "fails"],
    instructions: "Diagnose the likely cause from the error and code, explain why it happens, and give a corrected snippet. Suggest how to verify the fix.",
  },
  {
    id: "write-script",
    name: "Write a Script",
    category: "Coding",
    description: "Write a small program or automation.",
    triggers: ["write a script", "automate", "script to", "program to", "write code to"],
    instructions: "Clarify the language and goal, then write a clean, commented script. Note prerequisites and how to run it, preferring standard libraries.",
  },
  {
    id: "code-review",
    name: "Review Code",
    category: "Coding",
    description: "Review code for quality and bugs.",
    triggers: ["review my code", "code review", "improve this code", "is this code good"],
    instructions: "Review for correctness, readability, security, and performance. Give concrete, prioritized suggestions with example fixes, and note what's already good.",
  },
  {
    id: "regex",
    name: "Build a Regex",
    category: "Coding",
    description: "Construct and explain a regex.",
    triggers: ["regex", "regular expression", "pattern to match", "regexp"],
    instructions: "Build the regular expression, explain each part, and give test examples of matches and non-matches. Note flavor differences if relevant.",
  },
  {
    id: "sql-query",
    name: "Write a SQL Query",
    category: "Coding",
    description: "Write and explain a SQL query.",
    triggers: ["sql", "select from", "database query", "write a query", "join tables"],
    instructions: "Write the SQL for the described result, explain the joins and filters, and state assumptions about the schema. Suggest indexes if relevant.",
  },
  {
    id: "convert-code",
    name: "Convert / Refactor Code",
    category: "Coding",
    description: "Port or refactor code safely.",
    triggers: ["convert to", "port to", "refactor", "rewrite in", "translate this code"],
    instructions: "Translate or refactor while preserving behavior. Highlight idiomatic changes for the target language and any behavioral caveats.",
  },
  {
    id: "spreadsheet-formula",
    name: "Spreadsheet Formula",
    category: "Coding",
    description: "Build Excel / Sheets formulas.",
    triggers: ["excel", "google sheets", "formula", "vlookup", "spreadsheet", "pivot"],
    instructions: "Provide the exact formula for Excel or Google Sheets, explain each argument, and give a tiny example. Offer a cleaner alternative if one exists.",
  },

  // ── Learning & Education ────────────────────────────────────────────────
  {
    id: "study-notes",
    name: "Make Study Notes",
    category: "Learning & Education",
    description: "Condense a topic into study notes.",
    triggers: ["study notes", "notes on", "revision", "cheat sheet", "study guide"],
    instructions: "Condense the topic into structured study notes: key terms, core concepts, and a quick-reference summary.",
  },
  {
    id: "flashcards",
    name: "Create Flashcards",
    category: "Learning & Education",
    description: "Generate Q&A flashcards.",
    triggers: ["flashcards", "quiz cards", "anki", "q and a cards"],
    instructions: "Generate Q&A flashcards covering the key facts. Keep questions atomic and answers concise, output as a clean list.",
  },
  {
    id: "quiz-me",
    name: "Quiz Me",
    category: "Learning & Education",
    description: "Interactive practice questions.",
    triggers: ["quiz me", "test me", "practice questions", "ask me questions"],
    instructions: "Ask questions one set at a time, wait for the answers, then grade with explanations. Adapt the difficulty to the user's performance.",
  },
  {
    id: "lesson-plan",
    name: "Lesson Plan",
    category: "Learning & Education",
    description: "Design a lesson or curriculum.",
    triggers: ["lesson plan", "teach", "curriculum", "syllabus", "course outline"],
    instructions: "Design a lesson with objectives, prerequisites, sequenced activities with timing, and an assessment, matched to the learner's level.",
  },
  {
    id: "language-practice",
    name: "Practice a Language",
    category: "Learning & Education",
    description: "Conversational language practice.",
    triggers: ["practice spanish", "learn french", "language practice", "conversation in", "practice my"],
    instructions: "Hold a graded conversation in the target language, correct mistakes gently, and provide translations and notes as needed.",
  },
  {
    id: "tutorial",
    name: "Step-by-Step Tutorial",
    category: "Learning & Education",
    description: "Walk through a how-to in order.",
    triggers: ["tutorial", "how to", "step by step", "walk me through", "guide me"],
    instructions: "Give numbered steps stating what to do and what to expect at each. Include prerequisites and common pitfalls.",
  },

  // ── Life & Personal ─────────────────────────────────────────────────────
  {
    id: "recipe",
    name: "Recipe / Cooking",
    category: "Life & Personal",
    description: "Provide a recipe with steps.",
    triggers: ["recipe", "how to cook", "make a dish", "ingredients for", "what can i cook"],
    instructions: "Provide a recipe with ingredient quantities, ordered steps, total time, and servings. Offer substitutions and dietary variants when asked.",
  },
  {
    id: "meal-plan",
    name: "Meal Plan",
    category: "Life & Personal",
    description: "Plan balanced meals with a grocery list.",
    triggers: ["meal plan", "weekly meals", "diet plan", "what to eat", "meal prep"],
    instructions: "Build a balanced meal plan to the user's calories, diet, and preferences, with a grocery list. Keep it practical and varied.",
  },
  {
    id: "travel-itinerary",
    name: "Travel Itinerary",
    category: "Life & Personal",
    description: "Plan a day-by-day trip.",
    triggers: ["itinerary", "trip to", "travel plan", "vacation", "things to do in", "visiting"],
    instructions: "Build a day-by-day itinerary balancing must-sees, pacing, and logistics, with rough timing and tips. Use web tools for current details.",
  },
  {
    id: "budget",
    name: "Budget Helper",
    category: "Life & Personal",
    description: "Build a personal budget.",
    triggers: ["budget", "expenses", "save money", "monthly spending", "track my money"],
    instructions: "Build a simple budget from income and expenses, categorize spending, flag overspending, and suggest realistic savings.",
  },
  {
    id: "workout",
    name: "Workout Plan",
    category: "Life & Personal",
    description: "Design a training plan.",
    triggers: ["workout", "exercise plan", "training plan", "gym routine", "fitness plan"],
    instructions: "Design a workout plan for the user's goal, level, and equipment, with sets and reps, a weekly split, and progression. Add a brief safety note.",
  },
  {
    id: "gift-ideas",
    name: "Gift Ideas",
    category: "Life & Personal",
    description: "Suggest tailored gift ideas.",
    triggers: ["gift", "present for", "what to buy", "birthday idea", "gift ideas"],
    instructions: "Suggest thoughtful gift ideas tailored to the recipient, occasion, and budget. Group by price and say why each one fits.",
  },
  {
    id: "personal-message",
    name: "Personal Letter / Message",
    category: "Life & Personal",
    description: "Write a heartfelt personal message.",
    triggers: ["write a letter", "message for", "birthday message", "thank you note", "condolence", "wishes"],
    instructions: "Write a sincere, appropriately-toned message for the occasion. Keep it personal and ask for a detail or two if it would help.",
  },
  {
    id: "wellness-info",
    name: "General Wellness Info",
    category: "Life & Personal",
    description: "Balanced general health information.",
    triggers: ["symptom", "health advice", "diet advice", "sleep better", "wellness", "is it healthy"],
    instructions: "Give general, balanced wellness information without alarm. Clearly recommend seeing a qualified professional for diagnosis or any serious concern.",
  },

  // ── Business & Marketing ────────────────────────────────────────────────
  {
    id: "business-plan",
    name: "Business Plan",
    category: "Business & Marketing",
    description: "Draft a lean business plan.",
    triggers: ["business plan", "startup idea", "business idea", "start a business"],
    instructions: "Draft a lean business plan: problem, solution, target market, value proposition, revenue model, go-to-market, and key risks.",
  },
  {
    id: "marketing-copy",
    name: "Marketing Copy / Ads",
    category: "Business & Marketing",
    description: "Write persuasive marketing copy.",
    triggers: ["ad copy", "marketing copy", "slogan", "headline", "promote", "advertisement"],
    instructions: "Write persuasive copy for the channel and audience: lead with the benefit, keep it punchy, and offer a few variants with different angles.",
  },
  {
    id: "product-description",
    name: "Product Description",
    category: "Business & Marketing",
    description: "Write a compelling product listing.",
    triggers: ["product description", "product listing", "sell this", "ecommerce listing"],
    instructions: "Write a benefit-led hook, key features as scannable bullets, and a closing nudge. Match the brand tone.",
  },
  {
    id: "pitch",
    name: "Elevator Pitch",
    category: "Business & Marketing",
    description: "Craft a concise pitch.",
    triggers: ["pitch", "elevator pitch", "pitch deck", "investor", "sell my idea"],
    instructions: "Craft a concise, compelling pitch: problem, solution, market, traction, and the ask. Tailor the length to the format (30 seconds versus a deck).",
  },
  {
    id: "customer-reply",
    name: "Customer Support Reply",
    category: "Business & Marketing",
    description: "Write empathetic support replies.",
    triggers: ["customer", "support reply", "respond to complaint", "refund request", "reply to customer"],
    instructions: "Write an empathetic, solution-focused reply: acknowledge the issue, give clear next steps, and keep a professional, on-brand tone.",
  },
  {
    id: "invoice-quote",
    name: "Invoice / Quote Draft",
    category: "Business & Marketing",
    description: "Draft an invoice or price quote.",
    triggers: ["invoice", "quote", "estimate", "bill the client", "price quote"],
    instructions: "Draft a clear invoice or quote with line items, quantities, rates, totals, terms, and dates. Flag any fields the user must fill in.",
  },
  {
    id: "job-description",
    name: "Job Description",
    category: "Business & Marketing",
    description: "Write a job posting.",
    triggers: ["job description", "hiring", "job posting", "role description", "job ad"],
    instructions: "Write a clear job posting: role summary, responsibilities, requirements split into must-have and nice-to-have, and a company and benefits blurb.",
  },
  {
    id: "negotiation",
    name: "Negotiation Help",
    category: "Business & Marketing",
    description: "Prepare for a negotiation.",
    triggers: ["negotiate", "ask for a raise", "counter offer", "salary negotiation"],
    instructions: "Prepare the negotiation: your goal and walkaway point, supporting evidence, framing, and a script for likely objections. Keep the tone collaborative.",
  },

  // ── Creative ────────────────────────────────────────────────────────────
  {
    id: "story-writing",
    name: "Creative Writing / Story",
    category: "Creative",
    description: "Write engaging fiction.",
    triggers: ["write a story", "fiction", "short story", "creative writing", "write a scene"],
    instructions: "Write engaging fiction to the prompt with a clear point of view, vivid but economical detail, and momentum. Match the genre, length, and tone.",
  },
  {
    id: "poem",
    name: "Write a Poem",
    category: "Creative",
    description: "Compose a poem.",
    triggers: ["poem", "poetry", "verse", "haiku", "write me a poem"],
    instructions: "Write a poem in the requested form and theme, minding rhythm and imagery and respecting any structural constraints such as a haiku or sonnet.",
  },
  {
    id: "image-prompt",
    name: "Image Generation Prompt",
    category: "Creative",
    description: "Craft a detailed image-gen prompt.",
    triggers: ["image prompt", "midjourney", "dall-e", "stable diffusion", "generate an image", "prompt for an image"],
    instructions: "Craft a detailed image prompt: subject, style, composition, lighting, mood, and quality modifiers. Offer a negative prompt when relevant.",
  },
  {
    id: "naming",
    name: "Naming / Slogans",
    category: "Creative",
    description: "Generate names and taglines.",
    triggers: ["name for", "naming", "brand name", "slogan", "tagline", "what should i call"],
    instructions: "Generate name or slogan options grouped by style (descriptive, abstract, playful). Keep them short and memorable and flag any obvious trademark risks.",
  },
];
